<div class="about">
	<section>
		<h1>Qui sommes-nous?</h1>
			<p><img src="img/about3.jpg" alt="about3">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum, quidem velit. Maxime dolorem laudantium, tempora molestias, eos voluptatem minima sed quisquam ipsa rerum dolores dolor quod eum omnis dignissimos. Esse. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam suscipit est, corporis eligendi. Cumque vitae possimus ipsum animi quidem, illum voluptatem illo corporis et, suscipit fuga voluptatum ipsa recusandae voluptate.</p>
		<hr>
	</section>
	<section>
		<h1>Notre mission</h1>
			<p><img src="img/about2.jpg" alt="about2">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum dicta quia modi, enim impedit minus facere, ducimus fugit reiciendis molestiae obcaecati, aliquam voluptas. Harum maxime voluptatem a, architecto ipsam ex. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reprehenderit magni eum, aliquam nemo quas et, sapiente, ratione quia, nesciunt accusamus numquam? Commodi assumenda laudantium minima architecto officiis. Reprehenderit, ex, magnam.</p>
	    <hr>
	</section>
	<section>
		<h1>Notre objectif</h1>
			<p><img src="img/about1.jpg" alt="about1">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate vero numquam id in maxime laboriosam, quasi iusto amet magni dolorem voluptatem possimus, itaque beatae delectus. Deleniti quisquam perferendis id, laudantium. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consectetur enim sunt mollitia similique hic odio obcaecati dolorem ullam ab, laboriosam, excepturi dignissimos fugiat libero quas suscipit sint at a laudantium!</p>
		<hr>
	</section>
</div>