<div class="destinations">
	<div class="row">
		<?php foreach ($destinations as $destination): ?>
			<div class="col-lg-6 col-sm-12">
				<section>
					<a href="destination.php?id=<?= htmlspecialchars($destination['ID']) ?>" >
						<img src="img/<?=htmlspecialchars($destination['picture']) ?>" alt="img">
						<h2><?= htmlspecialchars($destination['title']) ?><i class="fas fa-heart"></i></h2>
						<p><?= substr(htmlspecialchars($destination['description']), 0, 220)?>  [...]</p>
					</a>
					<hr>
				</section>
			</div>	
		<?php endforeach ?>
	</div>
</div>