<div class="contact">
	<h1>Contactez-nous<i class="fas fa-heart"></i></h1>
	<p>Pour améliorer nos services et ainsi mieux vous satisfaire, nous serons toujours à l'écoute de vos commentaires, suggestions et interrogations. N'hésitez pas à nous consulter:</p>
		<ul>
			<li>Par courrier: BP 67000 Strasbourg - FRANCE</li>
			<li>Par téléphone: 0033 (0) 0 11 00 00 11 (Lundi au vendredi 9h-12h /14h-18h)</li>
			<li>Par courriel: travelitsforus@gmail.com</li>
		</ul>
</div>