<div class="destinations">
	<div class="row">
			<?php foreach ($destinations as $destination): ?>
			<div class="col-lg-4 col-sm-6">
				<section>
					<a href="destination.php?id=<?= $destination['ID'] ?>" >
						<img src="frontend/img/<?= htmlspecialchars($destination['picture']) ?>" alt="img">
						<h2><?= htmlspecialchars($destination['title']) ?></h2>
						<p><?= htmlspecialchars(substr($destination['description'], 0, 295))?>  [...] </p>
					</a>
					<hr>
				</section>

			</div>	
		<?php endforeach ?>
	</div>
</div>

