<div class="user-connect">
	
<?php if(isset($message)){ echo $message; } ?> <!--  pour afficher les erreures pendant la connexion -->

	<form action="userconnect.php" method="post">
		<ul>
			<li>
				<label for="email"></label>
				<input type="email" id='email' name='email' placeholder="E-mail *">
			</li>
			<li>
				<label for="password"></label>
				<input type="password" id='password' name='password' placeholder="Mot de passe *">
			</li>
			<li>
				<input class='send' type="submit" name="enter" value='ENVOYER' >
			</li>
		</ul>
		
	</form>
</div>